eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
    debug: true
    application:
        name: "le-customer"
    cloud:
        config:
            enabled: false
    jpa:
        show-sql: true
    logging:
        level:
            org.hibernate.SQL: DEBUG
            org.springframework: DEBUG
    h2:
        console:
            enabled: true

debug: true