/**
 *
 */
package org.jaravan.leproduct;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

/**
 * @author jayant
 *
 */
@Entity(name = "product")
public class Product implements Serializable {

    /**
     * Default generated serial version ID.
     */
    private static final long serialVersionUID = -4090891524682835472L;

    /**
     * Unique Identifier auto generated by JPA.
     */
    @Column(name = "id")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    /**
     * Name of the product.
     */
    @Column(name = "pname")
    @NotBlank
    private String name;

    /**
     * Short description of the product.
     */
    @NotBlank
    @Column(name = "short_desc")
    private String shortDescription;

    /**
     * Detailed description of product.
     */
    @NotBlank
    @Column(name = "description")
    private String description;

    /**
     * Quantity that can be ordered.
     */
    @Column(name = "quantity")
    private int quantity;

    /**
     * Price of the product.
     */
    @Column(name = "price")
    private BigDecimal price;

    /**
     * Default constructor.
     */
    public Product() {
    }

    /**
     * @param productId - Unique product ID.
     * @param productName - Name of the product.
     * @param shortDesc - Short description of product.
     * @param desc - Detailed description of product.
     * @param maxQuantity - Quantity that can be ordered.
     * @param productPrice - Price of the product.
     */
    public Product(final long productId,
            @NotBlank final String productName,
            @NotBlank final String shortDesc,
            @NotBlank final String desc,
            final int maxQuantity,
            final BigDecimal productPrice) {
        super();
        this.id = productId;
        this.name = productName;
        this.shortDescription = shortDesc;
        this.description = desc;
        this.quantity = maxQuantity;
        this.price = productPrice;
    }

    /**
     * @return the id
     */
    public long getId() {
        return id;
    }

    /**
     * @param productId the id to set
     */
    public void setId(final long productId) {
        this.id = productId;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param productName the name to set
     */
    public void setName(final String productName) {
        this.name = productName;
    }

    /**
     * @return the shortDescription
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * @param shortDesc the short description to set
     */
    public void setShortDescription(final String shortDesc) {
        this.shortDescription = shortDesc;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param desc the detailed description to set
     */
    public void setDescription(final String desc) {
        this.description = desc;
    }

    /**
     * @return the quantity
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * @param maxQuantity the maxQuantity to set
     */
    public void setQuantity(final int maxQuantity) {
        this.quantity = maxQuantity;
    }

    /**
     * @return the price
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * @param productPrice the price to set
     */
    public void setPrice(final BigDecimal productPrice) {
        this.price = productPrice;
    }
}
