eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
    port: 8082

spring:
    application:
        name: "le-order"
    cloud:
        config:
            enabled: false